// <auto-generated />
using System;
using ContosoAssets.SolutionManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContosoAssets.SolutionManagement.Migrations.CustomerManagementDb
{
    [DbContext(typeof(CustomerManagementDbContext))]
    [Migration("20190809180818_InitializeCustomerManagement")]
    partial class InitializeCustomerManagement
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.AppUse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company");

                    b.Property<Guid>("CustomerUserId");

                    b.Property<string>("Operation");

                    b.Property<DateTimeOffset>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("CustomerUserId");

                    b.ToTable("Usages");
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CustomerName");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.CustomerUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedDate");

                    b.Property<Guid>("CustomerId");

                    b.Property<string>("CustomerName");

                    b.Property<int?>("CustomerRegion");

                    b.Property<string>("ExternalUserName");

                    b.Property<string>("FullName");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerUsers");
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<double>("MonthlyCost");

                    b.Property<int>("MonthlyLimit");

                    b.Property<string>("Name");

                    b.Property<int>("SalesChannel");

                    b.HasKey("Id");

                    b.ToTable("Skus");

                    b.HasData(
                        new
                        {
                            Id = new Guid("097af8ee-f0a3-4d94-9a2b-56286f40ae26"),
                            Description = "None",
                            MonthlyCost = 0.0,
                            MonthlyLimit = 2147483647,
                            Name = "None",
                            SalesChannel = 2
                        },
                        new
                        {
                            Id = new Guid("74b32656-6cea-4643-a62c-df18e18df51f"),
                            Description = "Silver",
                            MonthlyCost = 9.9900000000000002,
                            MonthlyLimit = 2,
                            Name = "Silver",
                            SalesChannel = 0
                        },
                        new
                        {
                            Id = new Guid("1f1e7f72-c872-48c1-8fe1-10c2002c24a9"),
                            Description = "Gold",
                            MonthlyCost = 19.989999999999998,
                            MonthlyLimit = 5,
                            Name = "Gold",
                            SalesChannel = 0
                        },
                        new
                        {
                            Id = new Guid("2b014a1b-367b-4c35-b3b9-49b9f64af818"),
                            Description = "Platinum",
                            MonthlyCost = 29.989999999999998,
                            MonthlyLimit = 7,
                            Name = "Platinum",
                            SalesChannel = 0
                        },
                        new
                        {
                            Id = new Guid("f67febe9-547d-4c51-b82e-53bac023b938"),
                            Description = "Silver",
                            MonthlyCost = 9.9900000000000002,
                            MonthlyLimit = 2,
                            Name = "Silver",
                            SalesChannel = 1
                        },
                        new
                        {
                            Id = new Guid("f9b76781-a083-45c3-91c5-95074b7c944a"),
                            Description = "Gold",
                            MonthlyCost = 19.989999999999998,
                            MonthlyLimit = 5,
                            Name = "Gold",
                            SalesChannel = 1
                        },
                        new
                        {
                            Id = new Guid("0f9f58e5-43ed-4400-a967-17dfccceef8c"),
                            Description = "Platinum",
                            MonthlyCost = 29.989999999999998,
                            MonthlyLimit = 7,
                            Name = "Platinum",
                            SalesChannel = 1
                        });
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedTime");

                    b.Property<Guid>("CustomerId");

                    b.Property<DateTimeOffset>("LastOperationTime");

                    b.Property<string>("OfferId");

                    b.Property<string>("PlanId");

                    b.Property<int>("Quantity");

                    b.Property<Guid>("SkuId");

                    b.Property<int>("State");

                    b.Property<string>("SubscriptionName");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SkuId");

                    b.ToTable("CustomerSubscriptions");
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.AppUse", b =>
                {
                    b.HasOne("ContosoAssets.SolutionManagement.Data.CustomerUser", "CustomerUser")
                        .WithMany("Usages")
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.CustomerUser", b =>
                {
                    b.HasOne("ContosoAssets.SolutionManagement.Data.Customer", "Customer")
                        .WithMany("Users")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ContosoAssets.SolutionManagement.Data.Subscription", b =>
                {
                    b.HasOne("ContosoAssets.SolutionManagement.Data.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ContosoAssets.SolutionManagement.Data.Sku", "Sku")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
